[project]
name = "spotify-analytics"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.9",
    "django-allauth[socialaccount]>=65.13.1",
    "django-environ>=0.12.0",
    "psycopg2-binary>=2.9.11",
]
